### ISSUE TITLE
Uncaught Error: Connection is closed.

### ISSUE THREAD

**Issue by tommynsong** [atom/ide-csharp#17]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [ide-csharp](https://github.com/atom/ide-csharp) package 0.6.1

### Stack Trace

Uncaught Error: Connection is closed.

```
At C:\Users\tsong\.atom\packages\ide-csharp\node_modules\vscode-jsonrpc\lib\main.js:613

Error: Connection is closed.
    at /packages/ide-csharp/node_modules/vscode-jsonrpc/lib/main.js:138:28)
    at throwIfClosedOrDisposed (/packages/ide-csharp/node_modules/vscode-jsonrpc/lib/main.js:613:19)
    at Object.sendNotification (/packages/ide-csharp/node_modules/vscode-jsonrpc/lib/main.js:667:13)
    at LanguageClientConnection._sendNotification (/packages/ide-typescript/node_modules/atom-languageclient/build/lib/languageclient.js:365:15)
    at LanguageClientConnection.didChangeWatchedFiles (/packages/ide-typescript/node_modules/atom-languageclient/build/lib/languageclient.js:167:10)
    at ServerManager.projectFilesChanged (/packages/ide-typescript/node_modules/atom-languageclient/build/lib/server-manager.js:248:33)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at didChangeCallback (~/AppData/Local/atom/app-1.23.3/resources/app/src/project.js:350:28)
    at PathWatcher.onNativeEvents (~/AppData/Local/atom/app-1.23.3/resources/app/src/path-watcher.js:671:15)
    at ~/AppData/Local/atom/app-1.23.3/resources/app/src/path-watcher.js:567:31
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at NativeWatcher.onEvents (~/AppData/Local/atom/app-1.23.3/resources/app/src/path-watcher.js:448:26)
    at handler (~/AppData/Local/atom/app-1.23.3/resources/app/src/path-watcher.js:177:15)
```

### Commands

```
     -2:12.8.0 core:backspace (input.hidden-input)
     -1:51.7.0 core:copy (input.hidden-input)
     -1:41.5.0 core:paste (input.hidden-input)
     -1:14.7.0 markdown-writer:indent-list-line (input.hidden-input)
     -1:14.7.0 autocomplete-plus:confirm (input.hidden-input)
  2x -1:08.6.0 core:move-down (input.hidden-input)
     -1:08.1.0 markdown-writer:indent-list-line (input.hidden-input)
     -1:08.1.0 autocomplete-plus:confirm (input.hidden-input)
  4x -1:06.1.0 core:move-down (input.hidden-input)
     -0:54.8.0 markdown-writer:indent-list-line (input.hidden-input)
     -0:54.8.0 autocomplete-plus:confirm (input.hidden-input)
     -0:44.8.0 markdown-writer:indent-list-line (input.hidden-input)
     -0:44.8.0 autocomplete-plus:confirm (input.hidden-input)
     -0:43.4.0 core:move-right (input.hidden-input)
  2x -0:42.8.0 core:move-down (input.hidden-input)
     -0:26.1.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.9 
atom-ide-ui 0.7.1 
atom-material-ui 2.1.1 
editorconfig 2.2.2 
file-icons 2.1.15 
ide-csharp 0.6.1 
ide-css 0.2.0 
ide-flowtype 0.17.6 
ide-go 0.4.0 
ide-html 0.4.1 
ide-json 0.1.0 
ide-python 0.5.0 
ide-typescript 0.7.2 
ide-yaml 0.4.2 
language-logstash 0.1.7 
language-terraform 0.8.1 
linter-terraform-syntax 1.2.2 
markdown-preview-plus 2.4.16 
markdown-writer 2.7.3 
monokai 0.24.0 
node-debugger 1.10.1 
platformio-ide-terminal 2.8.0 
project-manager 3.3.5 
teletype 0.5.0 
terraform-fmt 0.3.0 
```

**Comment by rsese** [comment]
Thanks for the report - do you remember what you were doing before the error?  If so, is the error reproducible for you?

**Comment by tommynsong** [comment]
I was editing a javascript file and upon saving the file, I got the error.

**Comment by rsese** [comment]
Thanks @tommynsong - so just to confirm, it sounds like you hit this error once but haven't seen it since when saving files?

**Comment by tommynsong** [comment]
at the time, it was happening persistently, even after the extension is removed.
I have later on re-installed the extension and it does not appear to happen anymore.

**Comment by ogaaaan** [comment]
suddenly happened same issue while writing JavaScript Code.

```
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Unknown Windows version
**Thrown From**: [ide-csharp](https://github.com/atom/ide-csharp) package 0.6.1


### Stack Trace

Uncaught Error: Connection is closed.

```
At C:\Users\ogaaaan\.atom\packages\ide-csharp\node_modules\vscode-jsonrpc\lib\main.js:613

Error: Connection is closed.
    at /packages/ide-csharp/node_modules/vscode-jsonrpc/lib/main.js:138:28)
    at throwIfClosedOrDisposed (/packages/ide-csharp/node_modules/vscode-jsonrpc/lib/main.js:613:19)
    at Object.sendNotification (/packages/ide-csharp/node_modules/vscode-jsonrpc/lib/main.js:667:13)
    at LanguageClientConnection._sendNotification (/packages/ide-java/node_modules/atom-languageclient/build/lib/languageclient.js:365:15)
    at LanguageClientConnection.didChangeTextDocument (/packages/ide-java/node_modules/atom-languageclient/build/lib/languageclient.js:137:10)
    at TextEditorSyncAdapter.sendFullChanges (/packages/ide-java/node_modules/atom-languageclient/build/lib/adapters/document-sync-adapter.js:183:22)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at disposables.add.displayLayer.onDidChange.changes (~/AppData/Local/atom/app-1.23.3/resources/app/src/text-editor.js:588:26)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at DisplayLayer.emitDeferredChangeEvents (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/text-buffer/lib/display-layer.js:833:26)
    at TextBuffer.module.exports.TextBuffer.emitDidChangeTextEvent (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/text-buffer/lib/text-buffer.js:1682:30)
    at TextBuffer.module.exports.TextBuffer.transact (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/text-buffer/lib/text-buffer.js:964:18)
    at TextEditor.transact (~/AppData/Local/atom/app-1.23.3/resources/app/src/text-editor.js:1811:30)
    at TextEditor.moveCursors (~/AppData/Local/atom/app-1.23.3/resources/app/src/text-editor.js:2680:23)
    at TextEditor.setCursorScreenPosition (~/AppData/Local/atom/app-1.23.3/resources/app/src/text-editor.js:2491:23)
    at TextEditorComponent.didMouseDownOnContent (~/AppData/Local/atom/app-1.23.3/resources/app/src/text-editor-component.js:1810:25)
```

### Commands

```
  3x -3:49.7.0 core:move-up (input.hidden-input)
  3x -3:48.9.0 core:move-right (input.hidden-input)
     -3:48.4.0 core:delete (input.hidden-input)
  3x -3:47.2.0 core:move-down (input.hidden-input)
     -3:46.6.0 core:save (input.hidden-input)
     -3:44.3.0 docblockr:parse-tab (input.hidden-input)
     -3:44.3.0 snippets:next-tab-stop (input.hidden-input)
     -3:44.3.0 snippets:expand (input.hidden-input)
     -3:44.3.0 editor:indent (input.hidden-input)
  3x -3:41.4.0 core:backspace (input.hidden-input)
 13x -3:34.5.0 core:move-left (input.hidden-input)
     -3:33.1.0 core:delete (input.hidden-input)
     -3:33 editor:move-to-end-of-screen-line (input.hidden-input)
  2x -3:23.5.0 editor:select-to-first-character-of-line (input.hidden-input)
     -3:22.7.0 core:delete (input.hidden-input)
     -3:21.6.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.8.1 
build-papyrus 1.4.4 
docblockr 0.13.6 
document-outline 2.0.1 
editorconfig 2.2.2 
emmet 2.4.3 
file-icons 2.1.16 
highlight-selected 0.13.1 
ide-csharp 0.6.1 
ide-flowtype 0.18.0 
ide-java 0.7.0 
ide-php 0.7.5 
ide-typescript 0.7.2 
language-apache 1.8.0 
language-papyrus 2.0.9 
line-ending-converter 1.3.2 
markdown-preview-enhanced 0.15.2 
project-manager 3.3.5 
```

**Comment by ogaaaan** [comment]
1. Settings -> installed package
2. search "typescript"
3. disable "ide-typescript"

atom's error to be not displayed by this flow.
but, i guess that that is not resolv.

**Comment by ogaaaan** [comment]
hi!
i tryed update my atom.

i often edit java-script file.
so far, sometimes type script plugin error was happened.
but C# error was not display.

i can edit java script files now.
thanks update!

**Comment by WolfieMario** [comment]
I'm getting it when editing Powershell files with ide-powershell installed. ide-csharp is listening to notifications from other packages, and throwing in response.


**Atom**: 1.30.0 x64
**Electron**: 2.0.5
**OS**: Microsoft Windows 10 Home
**Thrown From**: [ide-csharp](https://github.com/atom/ide-csharp) package 0.6.2


### Stack Trace

Uncaught Error: Connection is closed.

```
At C:\Users\Gerrard\.atom\packages\ide-csharp\node_modules\vscode-jsonrpc\lib\main.js:613

Error: Connection is closed.
    at /packages/ide-csharp/node_modules/vscode-jsonrpc/lib/main.js:138:28)
    at throwIfClosedOrDisposed (/packages/ide-csharp/node_modules/vscode-jsonrpc/lib/main.js:613:19)
    at Object.sendNotification (/packages/ide-csharp/node_modules/vscode-jsonrpc/lib/main.js:667:13)
    at LanguageClientConnection._sendNotification (/packages/ide-powershell/node_modules/atom-languageclient/build/lib/languageclient.js:365:15)
    at LanguageClientConnection.didChangeTextDocument (/packages/ide-powershell/node_modules/atom-languageclient/build/lib/languageclient.js:137:10)
    at TextEditorSyncAdapter.sendIncrementalChanges (/packages/ide-powershell/node_modules/atom-languageclient/build/lib/adapters/document-sync-adapter.js:204:24)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.30.0/resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.30.0/resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at TextBuffer.module.exports.TextBuffer.emitDidChangeTextEvent (~/AppData/Local/atom/app-1.30.0/resources/app/node_modules/text-buffer/lib/text-buffer.js:1794:32)
    at TextBuffer.module.exports.TextBuffer.transact (~/AppData/Local/atom/app-1.30.0/resources/app/node_modules/text-buffer/lib/text-buffer.js:998:18)
    at TextEditor.transact (~/AppData/Local/atom/app-1.30.0/resources/app/src/text-editor.js:2002:30)
    at mergeIntersectingSelections (~/AppData/Local/atom/app-1.30.0/resources/app/src/text-editor.js:1429:25)
    at TextEditor.mergeSelections (~/AppData/Local/atom/app-1.30.0/resources/app/src/text-editor.js:3419:26)
    at TextEditor.mergeIntersectingSelections (~/AppData/Local/atom/app-1.30.0/resources/app/src/text-editor.js:3390:42)
    at TextEditor.mutateSelectedText (~/AppData/Local/atom/app-1.30.0/resources/app/src/text-editor.js:1428:23)
    at TextEditor.insertText (~/AppData/Local/atom/app-1.30.0/resources/app/src/text-editor.js:1381:31)
    at TextEditorComponent.didTextInput (~/AppData/Local/atom/app-1.30.0/resources/app/src/text-editor-component.js:1650:30)
```

### Commands

```
     -6:45 intentions:highlight (input.hidden-input)
     -6:44.9.0 core:copy (input.hidden-input)
  2x -6:43.6.0 intentions:highlight (input.hidden-input)
     -6:33.4.0 debugger:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -6:03.1.0 intentions:highlight (input.hidden-input)
     -6:02.8.0 core:paste (input.hidden-input)
     -5:59.9.0 intentions:highlight (input.hidden-input)
     -5:59.6.0 core:paste (input.hidden-input)
  2x -5:59.2.0 intentions:highlight (input.hidden-input)
     -5:56.4.0 core:paste (input.hidden-input)
     -4:33.5.0 intentions:highlight (input.hidden-input)
  2x -2:00.4.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
api-docs 0.0.6 
atom-beautify 0.32.2 
atom-ctags 5.1.2 
atom-formatter-jsbeautify 1.1.2 
atom-ide-ui 0.13.0 
atom-smart-template 0.3.2 
audio 1.5.7 
auto-id-class 0.7.1 
autoclose-html 0.23.0 
autocomplete-emojis 2.5.0 
bezier-curve-editor 0.7.2 
busy-signal 1.4.3 
clipboard-history 0.6.6 
code-peek 1.4.21 
color-picker 2.3.0 
cursor-history 0.13.1 
declarations 1.1.3 
declarations-js 1.0.2 
emmet 2.4.3 
file-icons 2.1.24 
file-templates 0.2.0 
formatter 2.12.4 
git-diff-details 1.4.0 
git-log 0.4.1 
git-plus 8.0.2 
git-time-machine 2.1.0 
goto 1.8.3 
goto-definition 1.3.4 
highlight-selected 0.14.0 
Hydrogen 2.5.1 
hyperclick 0.0.0 
hyperlink-hyperclick 2.0.0 
ide-csharp 0.6.2 
ide-css 0.3.0 
ide-html 0.4.2 
ide-java 0.8.3 
ide-json 0.2.1 
ide-powershell 0.1.0 
ide-python 1.0.0 
ide-typescript 0.7.6 
ide-vue 0.1.9 
intentions 1.1.5 
intentions-colorpicker 1.0.1 
js-hyperclick 1.13.3 
js-refactor 0.8.1 
jsformat 0.9.3 
jumpy 5.0.1 
language-autohotkey 0.1.0 
language-autohotkey2 1.0.1 
language-batchfile 0.7.5 
language-powershell 4.0.1 
language-vue 0.23.1 
last-cursor-position 0.9.3 
line-diff-details 1.9.0 
linter 2.2.0 
linter-autocomplete-jing 0.8.2 
linter-coffeelint 2.0.1 
linter-eslint 8.4.1 
linter-jsonlint 1.3.0 
linter-markdown 5.2.2 
linter-package-json-validator 2.0.0 
linter-proselint 3.3.0 
linter-pycodestyle 2.1.3 
linter-pydocstyle 0.4.7 
linter-pylint 2.1.1 
linter-stylelint 4.3.2 
linter-tidy 2.3.1 
linter-ui-default 1.7.1 
local-history 4.3.1 
minimap 4.29.8 
minimap-autohider 1.5.4 
minimap-bookmarks 0.4.2 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-linter 2.1.3 
minimap-selection 4.5.0 
minimap-split-diff 0.3.7 
open-recent 5.0.0 
platformio-ide-terminal 2.8.4 
project-manager 3.3.6 
recent-files-fuzzy-finder 0.6.1 
refactor 0.11.5 
revert-buffer 0.6.0 
sort-lines 0.18.0 
split-diff 1.5.2 
styles-highlighter 2.4.0 
svg-preview 0.12.1 
symbols-view-plus 0.117.0-plus.1 
template-generator 0.16.0 
terminal-tab-service 0.1.4 
toggle-quotes 1.1.1 
web-search 0.3.3 
wordcount 3.0.0 
zentabs 0.8.9 
```
