### ISSUE TITLE
Uncaught SyntaxError: Unexpected token < in JSON at position 1

### ISSUE THREAD

**Issue by erbridge** [atom/ide-csharp#18]
[Enter steps to reproduce:]

1. Unclear, but seems to occur when Atom loses focus.

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: "Arch Linux"
**Thrown From**: [ide-csharp](https://github.com/atom/ide-csharp) package 0.6.1

### Stack Trace

Uncaught SyntaxError: Unexpected token < in JSON at position 1

```
At file:///usr/lib/atom/static/index.html:2

SyntaxError: Unexpected token < in JSON at position 1
    at JSON.parse (<anonymous>)
    at StreamMessageReader.onData (/packages/ide-csharp/node_modules/vscode-jsonrpc/lib/messageReader.js:219:29)
    at /packages/ide-csharp/node_modules/vscode-jsonrpc/lib/messageReader.js:185:19)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:551:20)
```

### Commands

```
     -9:21.1.0 intentions:highlight (input.hidden-input)
     -9:20.9.0 core:save (input.hidden-input)
     -3:45.6.0 intentions:highlight (input.hidden-input)
     -3:45.4.0 find-and-replace:show (input.hidden-input)
  3x -3:45 core:confirm (input.hidden-input)
     -2:03.6.0 intentions:highlight (input.hidden-input)
     -2:03.4.0 project-find:show (input.hidden-input)
  3x -2:01.1.0 core:backspace (input.hidden-input)
     -1:58.2.0 core:confirm (input.hidden-input)
  2x -1:52.1.0 core:backspace (input.hidden-input)
     -1:51.2.0 core:confirm (input.hidden-input)
     -0:55 intentions:highlight (input.hidden-input)
     -0:54.9.0 find-and-replace:show (input.hidden-input)
     -0:54.6.0 core:confirm (input.hidden-input)
     -0:38.3.0 intentions:highlight (input.hidden-input)
     -0:37.7.0 core:close (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.7 
atom-beautify 0.30.9 
atom-clock 0.1.16 
atom-ide-ui 0.7.1 
atom-ternjs 0.18.3 
atom-ungit 0.6.0 
atomatigit 1.5.5 
auto-detect-indentation 1.3.0 
autocomplete-glsl 0.2.3 
autocomplete-json 5.5.2 
autocomplete-modules 1.8.0 
autocomplete-paths 2.12.1 
autocomplete-python 1.10.5 
base16-syntax 1.8.1 
build 0.70.0 
busy 0.7.0 
busy-signal 1.4.3 
dash 1.7.1 
duplicate-line-or-selection 0.9.0 
editorconfig 2.2.2 
figlet 0.5.4 
file-icons 2.1.15 
git-control 0.9.0 
git-panel 0.0.0 
git-plus 7.10.0 
git-time-machine 1.5.9 
go-debug 1.5.3 
go-plus 5.7.2 
go-signature-statusbar 1.2.3 
hyperclick 0.0.0 
hyperlink-hyperclick 1.3.4 
ide-csharp 0.6.1 
ide-flowtype 0.17.6 
ide-rust 0.8.0 
intentions 1.1.5 
js-hyperclick 1.12.2 
language-antlr4 0.1.0 
language-diff 0.7.0 
language-docker 1.1.8 
language-ink 0.1.0 
language-lua 0.9.11 
language-rust 0.4.12 
language-shadercode-shaderlab 2.0.1 
language-sln 0.1.0 
language-stylus 0.2.0 
language-webidl 0.1.0 
line-ending-converter 1.3.2 
linter 2.2.0 
linter-docker 0.3.0 
linter-eslint 8.4.0 
linter-gcc 0.7.1 
linter-jsonlint 1.3.0 
linter-markdown 5.2.0 
linter-pylama 0.9.5 
linter-sass-lint 1.8.3 
linter-shellcheck 1.4.6 
linter-tidy 2.3.1 
markdown-writer 2.7.3 
merge-conflicts 1.4.5 
nucleus-dark-ui 0.12.3 
pigments 0.40.2 
prettier-atom 0.46.0 
pretty-json 1.6.4 
project-plus 1.0.0 
proto-repl 1.4.22 
react 0.17.0 
sort-lines 0.18.0 
split-diff 1.5.2 
teletype 0.5.0 
todo-show 2.1.0 
toggle-quotes 1.1.0 
tool-bar 1.1.4 
tool-bar-markdown-writer 0.3.1 
travis-ci-status 1.3.1 
tree-view-git-status 1.4.0 
```

**Comment by rsese** [comment]
Thanks for the report - to clarify, you just switched to another application and this error popped up in Atom while you were working on a C# project?  Also, did you hit this just the one time or have you seen it multiple times?

**Comment by erbridge** [comment]
I've seen it a few times, and each time it was already there when I returned to Atom, so I never actually saw it pop up.
