### ISSUE TITLE
Failed to load the ide-csharp package

### ISSUE THREAD

**Issue by adrian-stepien** [atom/ide-csharp#2]
1. Install atom-ide-ui
2. Install ide-csharp
3. Restart atom

**Atom**: 1.21.0-beta0 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [ide-csharp](https://github.com/atom/ide-csharp) package 0.6.0

### Stack Trace

Failed to load the ide-csharp package

```
At Cannot find module 'vscode-jsonrpc'

Error: Cannot find module 'vscode-jsonrpc'
  at Module._resolveFilename (module.js:470:15)
  at Module._resolveFilename (~/AppData/Local/atom/app-1.21.0-beta0/resources/electron.asar/common/reset-search-paths.js:35:12)
  at Function.get_Module._resolveFilename (<embedded>:11237:58)
  at Module.require (/app.asar/static/index.js:40:43)
  at require (<embedded>:10582:33)
  at /packages/ide-csharp/node_modules/atom-languageclient/build/lib/languageclient.js:6:22)
  at /packages/ide-csharp/node_modules/atom-languageclient/build/lib/languageclient.js:491:3)
  at Module.get_Module._compile (<embedded>:10622:36)
  at Object.value [as .js] (<embedded>:10873:29)
  at Module.load (module.js:488:32)
  at tryModuleLoad (module.js:447:12)
  at Function.Module._load (module.js:439:3)
  at Module.require (/app.asar/static/index.js:47:45)
  at require (<embedded>:10582:33)
  at /packages/ide-csharp/node_modules/atom-languageclient/build/lib/auto-languageclient.js:10:23)
  at /packages/ide-csharp/node_modules/atom-languageclient/build/lib/auto-languageclient.js:430:3)
  at Module.get_Module._compile (<embedded>:10622:36)
  at Object.value [as .js] (<embedded>:10873:29)
  at Module.load (module.js:488:32)
  at tryModuleLoad (module.js:447:12)
  at Function.Module._load (module.js:439:3)
  at Module.require (/app.asar/static/index.js:47:45)
  at require (<embedded>:10582:33)
  at /packages/ide-csharp/node_modules/atom-languageclient/build/lib/main.js:1:182)
  at /packages/ide-csharp/node_modules/atom-languageclient/build/lib/main.js:26:3)
  at Module.get_Module._compile (<embedded>:10622:36)
  at Object.value [as .js] (<embedded>:10873:29)
  at Module.load (module.js:488:32)
  at tryModuleLoad (module.js:447:12)
  at Function.Module._load (module.js:439:3)
  at Module.require (/app.asar/static/index.js:47:45)
  at require (<embedded>:10582:33)
  at /packages/ide-csharp/lib/main.js:1:185)
  at /packages/ide-csharp/lib/main.js:15:3)
  at Module.get_Module._compile (<embedded>:10622:36)
  at Object.value [as .js] (<embedded>:10873:29)
  at Module.load (module.js:488:32)
  at tryModuleLoad (module.js:447:12)
  at Function.Module._load (module.js:439:3)
  at Module.require (/app.asar/static/index.js:47:45)
  at require (internal/module.js:20:19)
  at customRequire (<embedded>:96:26)
  at Package.module.exports.Package.requireMainModule (<embedded>:70636:35)
  at <embedded>:69891:34
  at Package.module.exports.Package.measure (<embedded>:69832:21)
  at Package.module.exports.Package.load (<embedded>:69877:18)
  at PackageManager.loadAvailablePackage (<embedded>:23818:16)
  at config.transact (<embedded>:23731:20)
  at Config.module.exports.Config.transact (<embedded>:20764:22)
  at PackageManager.loadPackages (<embedded>:23729:23)
  at <embedded>:1059:34

```

### Commands

```
```

### Non-Core Packages

```
atom-ide-ui 0.3.0 
ex-mode 0.18.0 
ide-csharp 0.6.0 
ide-haskell 2.0.5 
vim-mode 0.66.0 
```

**Comment by damieng** [comment]
Can you take a look in the ide-csharp\node_modules folder and see if vscode-jsonrpc is in there?  It's a pacakge dependency of atom-languageclient so I'm confused how it didn't get installed.

**Comment by qmmp123** [comment]
https://github.com/OmniSharp/atom-languageclient/issues/1  look here

**Comment by damieng** [comment]
The OmniSharp/atom-languageclient has nothing to do with Atom IDE.  The OmniSharp team previously created their own bridge to Atom and it unfortunately has a similar name.

How did you install ide-csharp?  apm and atom are responsible for installing the necessary dependencies so it's strange that the vscode-jsonrpc package would not get installed.
