### ISSUE TITLE
Failed to activate the ide-csharp package

### ISSUE THREAD

**Issue by Soofadi** [atom/ide-csharp#21]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.28.0 x64
**Electron**: 2.0.3
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [ide-csharp](https://github.com/atom/ide-csharp) package 0.6.2

### Stack Trace

Failed to activate the ide-csharp package

```
At Invalid or unexpected token

SyntaxError: Invalid or unexpected token
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.28.0/resources/app/src/native-compile-cache.js:94:52)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.28.0/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.28.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/ide-csharp/lib/main.js:1:185)
    at /packages/ide-csharp/lib/main.js:15:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.28.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.28.0/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (~/AppData/Local/atom/app-1.28.0/resources/app/static/<embedded>:96:26)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.28.0/resources/app/src/package.js:782:33)
    at Package.activateNow (~/AppData/Local/atom/app-1.28.0/resources/app/src/package.js:220:40)
    at measure (~/AppData/Local/atom/app-1.28.0/resources/app/src/package.js:206:33)
    at Package.measure (~/AppData/Local/atom/app-1.28.0/resources/app/src/package.js:88:25)
    at activationPromise.Promise (~/AppData/Local/atom/app-1.28.0/resources/app/src/package.js:200:20)
    at new Promise (<anonymous>)
    at Package.activate (~/AppData/Local/atom/app-1.28.0/resources/app/src/package.js:198:38)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.28.0/resources/app/src/package-manager.js:695:42)
    at config.transactAsync (~/AppData/Local/atom/app-1.28.0/resources/app/src/package-manager.js:670:36)
    at Config.transactAsync (~/AppData/Local/atom/app-1.28.0/resources/app/src/config.js:866:28)
    at PackageManager.activatePackages (~/AppData/Local/atom/app-1.28.0/resources/app/src/package-manager.js:668:23)
    at PackageManager.activate (~/AppData/Local/atom/app-1.28.0/resources/app/src/package-manager.js:647:50)
    at loadStatePromise.loadState.then (~/AppData/Local/atom/app-1.28.0/resources/app/src/atom-environment.js:871:27)
```

### Commands

```
```

### Non-Core Packages

```
atom-ide-debugger-native-gdb 0.7.2 
atom-ide-ui 0.12.0 
atom-shell-commands 1.5.0 
autocomplete-python 1.10.5 
busy 0.7.0 
busy-signal 1.4.3 
Hydrogen 2.5.1 
hydrogen-launcher 1.2.2 
hydrogen-python 0.0.6 
ide-bash 1.0.11 
ide-csharp 0.6.2 
ide-flowtype 0.23.0 
ide-java 0.8.3 
ide-json 0.2.1 
ide-php 0.7.14 
ide-python 1.0.0 
ide-typescript 0.7.6 
intentions 1.1.5 
java-classpath-registry 0.4.0 
java-generator 2.2.3 
linter 2.2.0 
linter-javac 1.9.4 
linter-python 3.1.2 
linter-ui-default 1.7.1 
my-package 0.0.0 
platformio-ide-terminal 2.8.3 
script 3.18.1 
teletype 0.13.3 
web-search 0.3.3 
```

**Comment by rsese** [comment]
Thanks for the report - did you get this error right after installing the package?  Can you try reinstalling and see if that helps?
