### ISSUE TITLE
Uncaught Error: Header must provide a Content-Length property.

### ISSUE THREAD

**Issue by lucianonooijen** [atom/ide-csharp#3]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.0-beta0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [ide-csharp](https://github.com/atom/ide-csharp) package 0.6.0

### Stack Trace

Uncaught Error: Header must provide a Content-Length property.

```
At /Users/lucianonooijen/.atom/packages/ide-csharp/node_modules/vscode-jsonrpc/lib/messageReader.js:191

Error: Header must provide a Content-Length property.
    at StreamMessageReader.onData (/packages/ide-csharp/node_modules/vscode-jsonrpc/lib/messageReader.js:191:27)
    at /packages/ide-csharp/node_modules/vscode-jsonrpc/lib/messageReader.js:176:19)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:551:20)
```

### Commands

```
     -0:32.4.0 command-palette:toggle (input.hidden-input)
     -0:30.3.0 core:confirm (input.hidden-input)
     -0:30.3.0 datatip:toggle (input.hidden-input)
     -0:27.9.0 command-palette:toggle (input.hidden-input)
     -0:26.6.0 editor:consolidate-selections (input.hidden-input)
     -0:26.6.0 core:cancel (input.hidden-input)
     -0:14.6.0 intentions:highlight (input.hidden-input)
     -0:14.5.0 datatip:toggle (input.hidden-input)
     -0:12.5.0 intentions:highlight (input.hidden-input)
     -0:12.5.0 datatip:toggle (input.hidden-input)
     -0:12 intentions:highlight (input.hidden-input)
     -0:11.9.0 datatip:toggle (input.hidden-input)
     -0:11.4.0 intentions:highlight (input.hidden-input)
     -0:11.4.0 datatip:toggle (input.hidden-input)
     -0:11.2.0 intentions:highlight (input.hidden-input)
     -0:11.1.0 datatip:toggle (input.hidden-input)
```

### Non-Core Packages

```
atom-alignment 0.13.0 
atom-beautify 0.30.5 
atom-bootstrap4 1.4.0 
atom-html-preview 0.2.2 
atom-ide-ui 0.3.1 
autoclose-html 0.23.0 
autocomplete-wordpress-hooks 0.2.3 
busy-signal 1.4.3 
color-picker 2.2.5 
emmet 2.4.3 
file-icons 2.1.11 
ftp-remote-edit 0.12.1 
git-plus 7.9.3 
highlight-selected 0.13.1 
ide-csharp 0.6.0 
ide-java 0.6.0 
ide-php 0.6.1 
ide-typescript 0.6.1 
intentions 1.1.5 
linter 2.2.0 
linter-ui-default 1.6.8 
minimap 4.29.6 
minimap-pigments 0.2.2 
monokai-seti 0.9.0 
open-recent 5.0.0 
php-cs-fixer 4.1.1 
pigments 0.40.2 
sass-autocompile 0.13.3 
wordpress-api 1.2.2 
```

**Comment by damieng** [comment]
Can you describe what you were doing at the time?

Was it working then stopped or just failed entirely at start-up?

**Comment by lucianonooijen** [comment]
I was working in Java but somehow it still showed up when I cmd-clicked on
a function. It was not on start-up but when I was working.

Met vriendelijke groet / best regards,

Luciano Nooijen

2017-09-13 17:21 GMT+02:00 Damien Guard <notifications@github.com>:

**Comment by damieng** [comment]
Did you mean then to report this in ide-java?  If so we have an issue I believe covers this at https://github.com/atom/ide-java/issues/8
