### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by qmmp123** [atom/ide-csharp#4]
I have just now installed this package and atom-language client and did not get any features. Sorry for stupid question, but I dont understand how to use it.

**Comment by damieng** [comment]
You need to also install the atom-ide-ui package.  Details on the features and how they are exposed can be found at http://blog.atom.io/2017/09/12/announcing-atom-ide.html

**Comment by qmmp123** [comment]
So I have installed atom-ide-ui but did not get autocomplete. Must I install anything else?

**Comment by damieng** [comment]
It should just be those two files.

Can you open the dev tools window in Atom and see if there are any errors there?  You can also turn on ide debugging there to see what's going on by typing `atom.config.set('core.debugLSP', true)` and restarting atom.

You should see messages about omnisharp starting as well as the requests and responses for autocomplete.

**Comment by qmmp123** [comment]
```
Uncaught (in promise) Error: Cannot find module '../node_modules/nsfw/node_modules/fs-extra/lib/index.js'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/home/qmmp123/Downloads/atom-beta-1.21.0-beta0-amd64/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/home/qmmp123/Downloads/atom-beta-1.21.0-beta0-amd64/resources/app/src/module-cache.js:354:58)
    at Module.require (file:///home/qmmp123/%D0%97%D0%B0%D0%B3%D1%80%D1%83%D0%B7%D0%BA%D0%B8/atom-beta-1.21.0-beta0-amd64/resources/app.asar/static/index.js:40:43)
    at require (internal/module.js:20:19)
    at customRequire (/home/qmmp123/Downloads/atom-beta-1.21.0-beta0-amd64/resources/app/static/<embedded>:96:26)
    at get_fse (/home/qmmp123/Downloads/atom-beta-1.21.0-beta0-amd64/resources/app/node_modules/nsfw/lib/src/index.js:17:80)
    at Object.buildNSFW (/home/qmmp123/Downloads/atom-beta-1.21.0-beta0-amd64/resources/app/node_modules/nsfw/lib/src/index.js:88:16)
    at nsfw (/home/qmmp123/Downloads/atom-beta-1.21.0-beta0-amd64/resources/app/node_modules/nsfw/lib/src/index.js:33:37)
    at NSFWBackend.<anonymous> (/home/qmmp123/Downloads/atom-beta-1.21.0-beta0-amd64/resources/app/src/path-watcher.js:192:34)
    at Generator.next (<anonymous>)
    at step (/home/qmmp123/Downloads/atom-beta-1.21.0-beta0-amd64/resources/app/src/path-watcher.js:5:279)
    at /home/qmmp123/Downloads/atom-beta-1.21.0-beta0-amd64/resources/app/src/path-watcher.js:5:449
    at NSFWBackend.<anonymous> (/home/qmmp123/Downloads/atom-beta-1.21.0-beta0-amd64/resources/app/src/path-watcher.js:5:105)
    at NativeWatcher.<anonymous> (/home/qmmp123/Downloads/atom-beta-1.21.0-beta0-amd64/resources/app/src/path-watcher.js:326:32)
    at Generator.next (<anonymous>)
    at step (/home/qmmp123/Downloads/atom-beta-1.21.0-beta0-amd64/resources/app/src/path-watcher.js:5:279)
    at /home/qmmp123/Downloads/atom-beta-1.21.0-beta0-amd64/resources/app/src/path-watcher.js:5:449
    at NativeWatcher.<anonymous> (/home/qmmp123/Downloads/atom-beta-1.21.0-beta0-amd64/resources/app/src/path-watcher.js:5:105)
    at NativeWatcher.onDidChange (/home/qmmp123/Downloads/atom-beta-1.21.0-beta0-amd64/resources/app/src/path-watcher.js:358:18)
    at PathWatcher.onDidChange (/home/qmmp123/Downloads/atom-beta-1.21.0-beta0-amd64/resources/app/src/path-watcher.js:566:37)
    at /home/qmmp123/Downloads/atom-beta-1.21.0-beta0-amd64/resources/app/src/path-watcher.js:575:24
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by qmmp123** [comment]
```
C# (OmniSharp) Server starting "/home/qmmp123/develop/learnSharp/learnSharp/"
/home/qmmp123/.atom/packages/ide-csharp/node_modules/atom-languageclient/build/lib/logger.js:27 C# (OmniSharp) starting child Node "/home/qmmp123/.atom/packages/ide-csharp/node_modules/omnisharp-client/languageserver/server.js"
/home/qmmp123/.atom/packages/ide-csharp/node_modules/atom-languageclient/build/lib/logger.js:27 C# (OmniSharp) rpc.sendRequest initialize sending Object
```

**Comment by 3Descape** [comment]
I don't get anything here as well. I enabled debugging, but don't get any errors, just the notification that the ide-php package started the server and  "rpc.sendRequest initialize sending".

**Comment by damieng** [comment]
Did you ever get an initialize received message?

**Comment by 3Descape** [comment]
well I wasn't a 100% correct. I do get the info in the bottom bar where it says "PHP (FelixFBecker) started". If I try code formatting or any action like find all references the working icon right next to it appears and stays there forever.. Then I need to kill Atom as it continious without ever doing anything visible. 
I use the 1.21.0-beta0 on win 10 x64 (user has admin rights) with the ide-php package. I also tried things like removing all packages by deleting them and only install the two required ones, install via apm install atom-ide-ui....

**Comment by jradxl** [comment]
Exactly my question too...
Having seen the news that Atom has an IDE, having installed Atom 1.21.0-beta2, atom-ide-ui and ide-csharp packages, and created a folder with helloworld.cs in it, how do I compile, run and debug the code?
Googling shows similar questions but no answers...
Is there a tutorial or video?
I'm used to Visual Studio 2017. Am I expecting too much of Atom-IDE?
Thx

**Comment by damieng** [comment]
There is no debug and run functionality yet - the program is still in early access.

You will however get auto-completion, outline view, find references, go to definition, compiler warnings and errors etc.

**Comment by JosephTLyons** [comment]
I still cannot get these packages to do anything for me.  My Atom experience is essentially the same with or without them installed / enabled.

I would like to use Atom to compile C# for Unity, but with the UI package and the Csharp package, nothing is happening.  No errors are reporting (even when purposely inserting some) and the outline view is disabled with message "no outline available: this is likely an error with the language package."

Any idea on how to get them working?

**Comment by damieng** [comment]
@JosephTLyons There is no compilation facility at this time.  

It should be autocompleting text, diagnostics/warning messages, outline view, code formatting, go to definition etc.   

It's definitely working for some people - I have not been able to repro the lack of initialization response some people are reporting. We need more details on people's configurations to figure out what the common factor is so we can fix it.

**Comment by JosephTLyons** [comment]
@damieng  - oops, I actually knew that Atom couldn't compile, someone corrected me on this before, but I totally forgot.  It does autocomplete text, but no warnings are showing up, no outline view, etcetera.

I will say that autocomplete feels a bit off to me, it requires that I type in at least 3 characters before a completion list even populates, while other editors / IDEs that I use only require one.

**Comment by JosephTLyons** [comment]
If it helps, I'm on Atom 1.22.0 and macOS 10.12.6.  Let me know if I can provide any other details, would really like to get provide any help I can to support this being fixed, as I would love to use Atom to code my C# projects.

**Comment by iamWing** [comment]
Got the same issue with @JosephTLyons with .cs files. Same error message says "No outline available. This is likely an error with the language package". Happens on both macOS 10.13.1 & Windows 10 version 1709 with Atom 1.22.1

**Comment by rsese** [comment]
I played with this a bit more so just dropping some notes - I found that if I have a project with just a simple test file on its own, the features don't work for me either.  E.g. with this test file:

```c#
using System;

namespace MyApp
{
    class MyProgram
    {
        static int five() {
            return 5;
        }
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World");
            Console.ReadLine();
            five();
        }
    }
}
```

I get empty hovers like in https://github.com/atom/ide-csharp/issues/15, diagnostics don't seem to work (e.g. if I remove a brace, there's no error reported), find references returns "Find References: No references found", etc.   This test file compiles fine and runs with `mcs` and `mono`.

I then downloaded the .NET SDK from https://www.microsoft.com/net/learn/get-started/macos and created a new project:

```
dotnet new console -o csharpTest
```

With the default file generated:

```c#
using System;

namespace csharpTest
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
        }
    }
}
```

Some of the functionality starts working - e.g. hovers aren't empty and removing a brace will generate an error, though the outline view still doesn't work.

I then noticed if I copied the .csproj file generated by `dotnet new` to my original single file project:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

</Project>
```

Then some of the IDE functionality starts working.

**Comment by JosephTLyons** [comment]
Is this still in active development?  Or has it been abandoned?

**Comment by daviwil** [comment]
Nope, not abandoned.  We've mainly been waiting for OmniSharp Roslyn to get native language server protocol support because the temporary shim we've been using has been a little unreliable.  The OmniSharp team recently released a beta with initial language server protocol support so I'll try to get that hooked up in February.

**Comment by JosephTLyons** [comment]
Goog to hear.  Appreciate the update @daviwil and will be looking forward to trying the new implementation when it is done.

**Comment by mdmnk** [comment]
Interested in seeing this fixed as I am having similar issues. If I open a small c# file (standalone or in a Unity project) I get none of the ide features. Open a larger file in a full project and I see the IDE features.

**Comment by kedare** [comment]
Same issue, nothing is working, just syntax color but no auto complete or anything else.
Tested on a blank "dotnet new" project

**Comment by rogersachan** [comment]
same here

**Comment by JosephTLyons** [comment]
@daviwil are there any updates to this?  Patiently waiting for the day that those of us with these issues will get to use the IDE features.

**Comment by Iakubovich** [comment]
I cannot find in atom search "atom-ide-ui". If I type "ide" then here a lot of results (ide-python; ide-haskell, ect), but there is nothing if I type "atom-ide-ui". What am l doing wrong?
